//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ScdIODB.rc
//
#define IDC_SKIP                        3
#define IDC_ID                          3
#define ID_SET                          3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   105
#define IDR_MODBUSTYPE                  106
#define IDD_DEVICE                      107
#define IDD_DEVICE_STATS                108
#define IDD_GROUP                       109
#define IDD_TAG                         110
#define IDD_PORT_STATS                  111
#define IDC_EDITBAR_STYLES              112
#define IDB_IMAGELIST                   113
#define IDB_SPLASH                      114
#define IDS_PROPSHT_CAPTION             115
#define IDD_TAGANLGDETAILS              200
#define IDD_TAGDIGDETAILS               201
#define IDD_TAGDIGALARM                 202
#define IDD_TAGANLGALARM                203
#define IDD_NEWSTYLE                    204
#define IDR_DEVICE_INSPECTOR            205
#define IDR_TAG_INSPECTOR               206
#define IDB_LOGO                        207
#define IDR_COLOR_EDITBAR               208
#define IDR_TOOLBAR                     209
#define IDD_COPY_TAG                    211
#define IDD_PORTS                       212
#define IDD_DIALOG1                     214
#define IDR_OPCSERVER                   215
#define IDC_STYLES                      1000
#define IDC_PORTS                       1000
#define IDC_PORT                        1001
#define IDC_BAUD                        1001
#define IDC_PORT2                       1002
#define IDC_PORT_PARITY                 1002
#define IDC_FLOW                        1003
#define IDC_PARITY                      1004
#define IDC_DATA                        1004
#define IDC_REDUNDANCY                  1005
#define IDC_STOP                        1005
#define IDC_STATISTICS                  1006
#define IDC_FRAME                       1007
#define IDC_OFFMSG                      1008
#define IDC_ENABLE_SCALING              1009
#define IDC_RANGE                       1010
#define IDC_OVERRUN                     1011
#define IDC_TIMEOUT                     1012
#define IDC_TIMEOUT2                    1013
#define IDC_MSGDELAY                    1013
#define IDC_MESSAGE                     1015
#define IDC_SIMULATION_TYPE             1016
#define IDC_NAME                        1017
#define IDC_SENT                        1018
#define IDC_ENABLE                      1018
#define IDC_DESCRIPTION                 1019
#define IDC_SENT_SEC                    1020
#define IDC_VALUE                       1020
#define IDC_OFFSET                      1021
#define IDC_RCVD                        1022
#define IDC_MANUAL_VALUE                1022
#define IDC_PRIORITY                    1023
#define IDC_RCVD_SEC                    1024
#define IDC_DATATYPE                    1026
#define IDC_SCALING_STYLE               1028
#define IDC_SCALING_SETTINGS            1030
#define IDC_SIMULATE                    1031
#define IDC_SCALING_DESCRIPTION         1032
#define IDC_ONVALUE                     1033
#define IDC_EXAMPLE                     1034
#define IDC_OFFVALUE                    1035
#define IDC_DIRECT                      1036
#define IDC_REVERSE                     1037
#define IDC_TYPE                        1038
#define IDC_INITVALUE                   1039
#define IDC_TYPE2                       1040
#define IDC_SDEADBAND                   1041
#define IDC_SMINEU                      1042
#define IDC_FLOAT                       1043
#define IDC_SMINRAW                     1044
#define IDC_FLOAT2                      1045
#define IDC_ONMSG                       1047
#define IDC_SMINRAW2                    1048
#define IDC_WORDSWAP                    1049
#define IDC_SMAXRAW                     1050
#define IDC_SONMSG                      1051
#define IDC_WORDSWAP2                   1052
#define IDC_SENGUNITS                   1053
#define IDC_SOFFMSG                     1054
#define IDC_ADDRESS                     1055
#define IDC_SLOGDEADBAND                1056
#define IDC_ALARMON                     1057
#define IDC_ADDRESS2                    1058
#define IDC_TIME                        1059
#define IDC_ALARMOFF                    1060
#define IDC_SMAXRAW2                    1061
#define IDC_NOALARM                     1062
#define IDC_SPRIORITY                   1063
#define IDC_DEBAND                      1065
#define IDC_MINEU                       1066
#define IDC_MINRAW                      1067
#define IDC_MAXEU                       1068
#define IDC_MAXRAW                      1070
#define IDC_LINEAR                      1071
#define IDC_SQUARE                      1072
#define IDC_ENGUNITS                    1073
#define IDC_LOGDEADBAND                 1074
#define IDC_ENABLELOLOALM               1075
#define IDC_ENABLELOW                   1076
#define IDC_ENABLEHIGH                  1077
#define IDC_ENABLEHIHI                  1078
#define IDC_LOLO                        1079
#define IDC_LOW                         1080
#define IDC_DEVIATION                   1081
#define IDC_HIHI                        1082
#define IDC_LOLOPRIOR                   1083
#define IDC_LOWPRIOR                    1084
#define IDC_HIGHPRIOR                   1085
#define IDC_HIHIPRIOR                   1086
#define IDC_VALUEDEAD                   1087
#define IDC_ENABLEMINOR                 1088
#define IDC_ENABLEMAJOR                 1089
#define IDC_MINOR                       1090
#define IDC_MAJOR                       1091
#define IDC_HIGH                        1092
#define IDC_ENABLERATE                  1093
#define IDC_MINORPRIOR                  1094
#define IDC_MAJORPRIOR                  1095
#define IDC_DEVDEADBAND                 1096
#define IDC_RATE                        1097
#define IDC_RATESEC                     1098
#define IDC_RATEMIN                     1099
#define IDC_RATEHOUR                    1100
#define IDC_RATEPRIOR                   1101
#define IDC_SVALDEAD                    1102
#define IDC_SDEVDEADBAND                1103
#define IDC_STYLES_LIST                 1104
#define IDC_NEW_STYLE                   1105
#define IDC_DEL_STYLE                   1106
#define IDC_PARENT_STYLE                1108
#define IDC_RENAME                      1111
#define IDC_OVERWRITE                   1112
#define IDC_TITLE                       1113
#define IDC_CURRENT                     1114
#define IDC_NEW                         1115
#define IDC_MANUAL_MODE                 1116
#define IDC_STRING_LENGTH               1117
#define IDC_STRING_LENGTH_TEXT          1118
#define ID_VIEW_STYLEBAR                32770
#define ID_VIEW_MONITOR                 32771
#define ID_ADD_NEWDEVICE                32772
#define ID_ADD_NEWGROUP                 32773
#define ID_ADD_NEWTAG                   32774
#define ID_EDIT_PORTS                   32775
#define ID_EDIT_STYLES                  32776
#define ID_EDIT_PROPERTIES              32777
#define ID_DEVICE_DELETE                32778
#define ID_DEVICE_NEWGROUP              32779
#define ID_DEVICE_NEWTAG                32780
#define ID_DEVICE_DIAGNOSTICS           32781
#define ID_DEVICE_STATISTICS            32782
#define ID_DEVICE_PROPERTIES            32783
#define ID_SUMMARY                      32783
#define ID_TAG_DELETE                   32784
#define ID_EDIT_DELETE                  32785
#define ID_EDIT_FINDTAGS                32786
#define ID_EDIT_BM_TOGGLE               32787
#define ID_EDIT_BM_NEXT                 32788
#define ID_EDIT_BM_PREV                 32789
#define ID_EDIT_BM_CLEARALL             32790
#define ID_EDIT_FINDINFILES             32791
#define ID_EDIT_INDENT                  32792
#define ID_EDIT_UNINDENT                32793
#define ID_UPDATEALL                    32796
#define ID_UPDATEALLRQST                32797
#define IDW_EDIT_BAR                    0xE806
#define IDS_VENDOR_INFO                 61204
#define IDS_OPC_E_INVALIDHANDLE         63000
#define IDS_OPC_E_BADTYPE               63001
#define IDS_OPC_E_PUBLIC                63002
#define IDS_OPC_E_BADRIGHTS             63003
#define IDS_OPC_E_UNKNOWNITEMID         63004
#define IDS_OPC_E_INVALIDITEMID         63005
#define IDS_OPC_E_INVALIDFILTER         63006
#define IDS_OPC_E_UNKNOWNPATH           63007
#define IDS_OPC_E_RANGE                 63008
#define IDS_OPC_E_DUPLICATENAME         63009
#define IDS_OPC_S_UNSUPPORTEDRATE       63010
#define IDS_OPC_S_CLAMP                 63011
#define IDS_OPC_S_INUSE                 63012
#define IDS_OPC_E_INVALIDCONFIGFILE     63013
#define IDS_OPC_E_NOTFOUND              63014

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        216
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1119
#define _APS_NEXT_SYMED_VALUE           118
#endif
#endif
