#if !defined(AFX_SSACTIVECELL_H__A934B7EB_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_)
#define AFX_SSACTIVECELL_H__A934B7EB_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSSActiveCell wrapper class

class CSSActiveCell : public COleDispatchDriver
{
public:
	CSSActiveCell() {}		// Calls COleDispatchDriver default constructor
	CSSActiveCell(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSSActiveCell(const CSSActiveCell& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetTop();
	void SetTop(long);
	long GetLeft();
	void SetLeft(long);
	long GetHeight();
	void SetHeight(long);
	long GetWidth();
	void SetWidth(long);
	CString GetStyleSet();
	void SetStyleSet(LPCTSTR);
	CString GetText();
	void SetText(LPCTSTR);
	VARIANT GetValue();
	void SetValue(const VARIANT&);
	CString GetSelText();
	void SetSelText(LPCTSTR);
	short GetSelLength();
	void SetSelLength(short);
	short GetSelStart();
	void SetSelStart(short);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SSACTIVECELL_H__A934B7EB_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_)
