#if !defined(AFX_SSCOLUMN_H__A934B7EF_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_)
#define AFX_SSCOLUMN_H__A934B7EF_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSSColumn wrapper class

class CSSColumn : public COleDispatchDriver
{
public:
	CSSColumn() {}		// Calls COleDispatchDriver default constructor
	CSSColumn(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSSColumn(const CSSColumn& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CString GetCaption();
	void SetCaption(LPCTSTR);
	long GetAlignment();
	void SetAlignment(long);
	long GetForeColor();
	void SetForeColor(long);
	long GetBackColor();
	void SetBackColor(long);
	long GetCase();
	void SetCase(long);
	CString GetNumberFormat();
	void SetNumberFormat(LPCTSTR);
	short GetFieldLen();
	void SetFieldLen(short);
	BOOL GetAllowSizing();
	void SetAllowSizing(BOOL);
	long GetHeadForeColor();
	void SetHeadForeColor(long);
	long GetHeadBackColor();
	void SetHeadBackColor(long);
	CString GetDataField();
	void SetDataField(LPCTSTR);
	float GetLeft();
	void SetLeft(float);
	float GetTop();
	void SetTop(float);
	BOOL GetLocked();
	void SetLocked(BOOL);
	CString GetText();
	void SetText(LPCTSTR);
	VARIANT GetValue();
	void SetValue(const VARIANT&);
	BOOL GetVisible();
	void SetVisible(BOOL);
	float GetWidth();
	void SetWidth(float);
	short GetDataType();
	void SetDataType(short);
	BOOL GetSelected();
	void SetSelected(BOOL);
	BOOL GetButtonsAlways();
	void SetButtonsAlways(BOOL);
	short GetLevel();
	void SetLevel(short);
	long GetStyle();
	void SetStyle(long);
	BOOL GetHasHeadForeColor();
	void SetHasHeadForeColor(BOOL);
	BOOL GetHasHeadBackColor();
	void SetHasHeadBackColor(BOOL);
	BOOL GetHasForeColor();
	void SetHasForeColor(BOOL);
	BOOL GetHasBackColor();
	void SetHasBackColor(BOOL);
	BOOL GetVertScrollBar();
	void SetVertScrollBar(BOOL);
	VARIANT GetTagVariant();
	void SetTagVariant(const VARIANT&);
	short GetListCount();
	void SetListCount(short);
	long GetDropDownHwnd();
	void SetDropDownHwnd(long);
	CString GetHeadStyleSet();
	void SetHeadStyleSet(LPCTSTR);
	CString GetStyleSet();
	void SetStyleSet(LPCTSTR);
	short GetPosition();
	void SetPosition(short);
	short GetGroup();
	void SetGroup(short);
	long GetCaptionAlignment();
	void SetCaptionAlignment(long);
	BOOL GetColChanged();
	void SetColChanged(BOOL);
	CString GetName();
	void SetName(LPCTSTR);
	short GetListIndex();
	void SetListIndex(short);
	long GetNullable();
	void SetNullable(long);
	CString GetMask();
	void SetMask(LPCTSTR);
	BOOL GetPromptInclude();
	void SetPromptInclude(BOOL);
	long GetClipMode();
	void SetClipMode(long);
	CString GetPromptChar();
	void SetPromptChar(LPCTSTR);

// Operations
public:
	CString CellText(const VARIANT& Bookmark);
	VARIANT CellValue(const VARIANT& Bookmark);
	void AddItem(LPCTSTR Item, const VARIANT& Index);
	void RemoveItem(short Index);
	void RemoveAll();
	CString GetList(short Index);
	void SetList(short Index, LPCTSTR lpszNewValue);
	void CellStyleSet(LPCTSTR StyleSet, const VARIANT& RowNum);
	BOOL IsCellValid();
	long GetItemData(short Index);
	void SetItemData(short Index, long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SSCOLUMN_H__A934B7EF_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_)
