#if !defined(AFX_SSGROUP_H__A934B7E9_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_)
#define AFX_SSGROUP_H__A934B7E9_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CSSGroupColumns;

/////////////////////////////////////////////////////////////////////////////
// CSSGroup wrapper class

class CSSGroup : public COleDispatchDriver
{
public:
	CSSGroup() {}		// Calls COleDispatchDriver default constructor
	CSSGroup(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSSGroup(const CSSGroup& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CString GetCaption();
	void SetCaption(LPCTSTR);
	long GetCaptionAlignment();
	void SetCaptionAlignment(long);
	BOOL GetAllowSizing();
	void SetAllowSizing(BOOL);
	float GetLeft();
	void SetLeft(float);
	float GetTop();
	void SetTop(float);
	BOOL GetVisible();
	void SetVisible(BOOL);
	float GetWidth();
	void SetWidth(float);
	BOOL GetSelected();
	void SetSelected(BOOL);
	long GetHeadForeColor();
	void SetHeadForeColor(long);
	long GetHeadBackColor();
	void SetHeadBackColor(long);
	BOOL GetHasHeadForeColor();
	void SetHasHeadForeColor(BOOL);
	BOOL GetHasHeadBackColor();
	void SetHasHeadBackColor(BOOL);
	VARIANT GetTagVariant();
	void SetTagVariant(const VARIANT&);
	CString GetHeadStyleSet();
	void SetHeadStyleSet(LPCTSTR);
	CString GetStyleSet();
	void SetStyleSet(LPCTSTR);
	short GetPosition();
	void SetPosition(short);
	CSSGroupColumns GetColumns();
	void SetColumns(LPDISPATCH);

// Operations
public:
	short ColPosition(short ColPos);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SSGROUP_H__A934B7E9_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_)
