#if !defined(AFX_SSGROUPCOLUMNS_H__A934B7E6_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_)
#define AFX_SSGROUPCOLUMNS_H__A934B7E6_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CSSColumn;

/////////////////////////////////////////////////////////////////////////////
// CSSGroupColumns wrapper class

class CSSGroupColumns : public COleDispatchDriver
{
public:
	CSSGroupColumns() {}		// Calls COleDispatchDriver default constructor
	CSSGroupColumns(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSSGroupColumns(const CSSGroupColumns& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetCount();
	void SetCount(short);

// Operations
public:
	void Remove(const VARIANT& Index);
	void Add(short Index);
	void RemoveAll();
	LPUNKNOWN _NewEnum();
	CSSColumn GetItem(const VARIANT& Index);
	void SetItem(const VARIANT& Index, LPDISPATCH newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SSGROUPCOLUMNS_H__A934B7E6_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_)
