#if !defined(AFX_SSSELBOOKMARKS_H__A934B7EA_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_)
#define AFX_SSSELBOOKMARKS_H__A934B7EA_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSSSelBookmarks wrapper class

class CSSSelBookmarks : public COleDispatchDriver
{
public:
	CSSSelBookmarks() {}		// Calls COleDispatchDriver default constructor
	CSSSelBookmarks(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSSSelBookmarks(const CSSSelBookmarks& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetCount();
	void SetCount(long);

// Operations
public:
	void Add(const VARIANT& Bookmark);
	void Remove(const VARIANT& Index);
	void RemoveAll();
	LPUNKNOWN _NewEnum();
	VARIANT GetItem(const VARIANT& Index);
	void SetItem(const VARIANT& Index, const VARIANT& newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SSSELBOOKMARKS_H__A934B7EA_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_)
