#if !defined(AFX_SSSTYLESET_H__A934B7ED_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_)
#define AFX_SSSTYLESET_H__A934B7ED_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSSStyleSet wrapper class

class CSSStyleSet : public COleDispatchDriver
{
public:
	CSSStyleSet() {}		// Calls COleDispatchDriver default constructor
	CSSStyleSet(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSSStyleSet(const CSSStyleSet& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	float GetPictureMetaHeight();
	void SetPictureMetaHeight(float);
	float GetPictureMetaWidth();
	void SetPictureMetaWidth(float);
	VARIANT GetForeColor();
	void SetForeColor(const VARIANT&);
	VARIANT GetBackColor();
	void SetBackColor(const VARIANT&);
	VARIANT GetPicture();
	void SetPicture(const VARIANT&);
	VARIANT GetAlignmentPicture();
	void SetAlignmentPicture(const VARIANT&);
	VARIANT GetAlignmentText();
	void SetAlignmentText(const VARIANT&);
	VARIANT GetFont();
	void SetFont(const VARIANT&);
	CString GetName();
	void SetName(LPCTSTR);

// Operations
public:
	void Reset();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SSSTYLESET_H__A934B7ED_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_)
