#if !defined(AFX_SSSTYLESETS_H__A934B7E7_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_)
#define AFX_SSSTYLESETS_H__A934B7E7_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CSSStyleSet;

/////////////////////////////////////////////////////////////////////////////
// CSSStyleSets wrapper class

class CSSStyleSets : public COleDispatchDriver
{
public:
	CSSStyleSets() {}		// Calls COleDispatchDriver default constructor
	CSSStyleSets(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSSStyleSets(const CSSStyleSets& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetCount();
	void SetCount(short);

// Operations
public:
	void Add(LPCTSTR Name);
	void Remove(const VARIANT& Index);
	void RemoveAll();
	CSSStyleSet GetItem(const VARIANT& Index);
	void SetItem(const VARIANT& Index, LPDISPATCH newValue);
	LPUNKNOWN _NewEnum();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SSSTYLESETS_H__A934B7E7_F944_11D2_BDE0_00A0C9ED9512__INCLUDED_)
