//================== SysCAD - Copyright Kenwalt (Pty) Ltd ===================
// $Nokeywords: $
//===========================================================================
// ==========================================================================

/*
         Resource Defines
*/

#define ID_DDECLIENT                   100
#define ID_DDESERVER                   101

/*
         Menu Selection Defines
*/

#define IDM_EXIT                       100
#define IDM_ABOUT                      103
#define IDM_SENDTEST                   104



#define IDR_SFEICON                    105

