//================== SysCAD - Copyright Kenwalt (Pty) Ltd ===================
// $Nokeywords: $
//===========================================================================
// generic Sfe DLL Interface

#ifndef __SFEDLL_H
#define __SFEDLL_H

#ifndef __SFE_SRVR_H
  #include "sfe_srvr.h"
#endif

typedef CSfeSrvr* (*fn_AddSfeSrvr)();

// =========================================================================
#endif
