using System;
using System.Xml;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace SVNAutomate
{
  class Program
  {
    static int RunSVN(string argument, out string output)
    {
      System.Diagnostics.Process proc = new System.Diagnostics.Process();
      proc.EnableRaisingEvents = false;
      proc.StartInfo.UseShellExecute = false;
      proc.StartInfo.RedirectStandardOutput = true;
      proc.StartInfo.RedirectStandardError = true;
      proc.StartInfo.CreateNoWindow = true;

      if (proc.StartInfo.EnvironmentVariables.ContainsKey("SVN_SSH"))
      {
        proc.StartInfo.EnvironmentVariables.Remove("SVN_SSH");
      }
      proc.StartInfo.EnvironmentVariables.Add("SVN_SSH", @"C:\\Program Files\\TortoiseSVN\\bin\\TortoisePlink.exe");

      proc.StartInfo.FileName = "C:\\Program Files\\Subversion\\bin\\svn.exe";
      proc.StartInfo.Arguments = argument;
      proc.Start();

      output = proc.StandardOutput.ReadToEnd();
      string error = proc.StandardError.ReadToEnd();

      if (error.Length > 0)
      {
        Console.Write(error);
        Console.ReadKey(false);
      }
     
      return proc.ExitCode;
    }

    static int Main(string[] args)
    {
      string info;

      int exitCode;

      // Other svn parameters of note:
      //exitCode = RunSVN("update --non-interactive", out update);
      //exitCode = RunSVN("log  --non-interactive --xml --limit 10", out log);

      exitCode = RunSVN("info  --non-interactive --xml", out info);
      if (exitCode != 0)
      {
        Console.WriteLine("Unable to run SVN, returned exit code: " + exitCode);
        return exitCode;
      }

      int errorLevel = -1;

      try
      {
        XmlDocument xmlInfo = new XmlDocument();
        xmlInfo.LoadXml(info);

        String revision = "N/A";

        foreach (XmlNode node in xmlInfo.ChildNodes)
          foreach (XmlNode innerNode in node.ChildNodes)
            if (innerNode.Name == "entry")
              foreach (XmlAttribute attribute in innerNode.Attributes)
                if (attribute.Name == "revision")
                {
                  revision = attribute.Value;
                  errorLevel = 0;
                }

        String svn_h = "//" + "\n" +
                       "// Generated by SVNAutomate." + "\n" +
                       "//" + "\n" + "\n" +
//                       "#ifndef __SVN_H" + "\n" +
//                       "#define __SVN_H" + "\n" + "\n" +
                       "#define SCD_PATCH_SVN " + revision;

        FileStream fileStream = new FileStream("svn.h", FileMode.Create);
        StreamWriter streamWriter = new StreamWriter(fileStream);
        streamWriter.Write(svn_h);
        streamWriter.Close();
        fileStream.Close();

        if (errorLevel != 0)
        {
          Console.WriteLine("Unable to find revision number:\n" + info);
        }
      }
      catch(Exception e)
      {
        Console.WriteLine("Unable to process XML: " + e.Message + "\n" + info);
      }

      return errorLevel;
    }
  }
}
