using System;
using System.Xml;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace SVNAutomate
{
  class Program
  {
    static int RunSVN(string argument, out string output)
    {
      System.Diagnostics.Process proc = new System.Diagnostics.Process();
      proc.EnableRaisingEvents = false;
      proc.StartInfo.UseShellExecute = false;
      proc.StartInfo.RedirectStandardOutput = true;
      proc.StartInfo.RedirectStandardError = true;
      proc.StartInfo.CreateNoWindow = true;

      if (proc.StartInfo.EnvironmentVariables.ContainsKey("SVN_SSH"))
      {
        proc.StartInfo.EnvironmentVariables.Remove("SVN_SSH");
      }
      proc.StartInfo.EnvironmentVariables.Add("SVN_SSH", @"C:\\Program Files\\TortoiseSVN\\bin\\TortoisePlink.exe");

      output = "";

      try
      {
        proc.StartInfo.FileName = "C:\\Program Files\\Subversion\\bin\\svn.exe";
        proc.StartInfo.Arguments = argument;
        proc.Start();
        proc.WaitForExit(10000);

        output = proc.StandardOutput.ReadToEnd();
        string error = proc.StandardError.ReadToEnd();

        if (proc.ExitCode != 0)
        {
          Console.WriteLine("Unable to run SVN command (have you installed the commandline subversion client?): " + error);
        }

        return proc.ExitCode;
      }
      catch (Exception e)
      {
        Console.WriteLine("Exception occurred in SVN process execution: " + e.Message);
        Console.WriteLine("Have you installed the commandline subversion client?");
        return 1;
      }
    }

    static int Main(string[] args)
    {
      bool forceUpdate = false; // don't update unless there is a change by default.
      bool didUpdate = false;
      string fileName = "svn.h"; // create svn.h in the current directory by default.
      string filePath = "";

      foreach (string arg in args)
      {
        if (arg.StartsWith("/")) // an option.
        {
          if (arg.EndsWith("force"))
            forceUpdate = true;
        }
        else // not an option, last non-option will end up in fileName.
          fileName = arg;
      }

      try
      {
        filePath = Path.GetFullPath(fileName);
      }
      catch (Exception e)
      {
        Console.WriteLine("Filename can't be mapped to full path: " + fileName);
        return 1;
      }

      string info;

      // Other svn parameters of note:
      //exitCode = RunSVN("update --non-interactive", out update);
      //exitCode = RunSVN("log  --non-interactive --xml --limit 10", out log);

      int error = RunSVN("info  --non-interactive --xml", out info);
      if (error != 0)
      {
        return error;
      }

      int errorLevel = 1;

      try
      {
        XmlDocument xmlInfo = new XmlDocument();
        xmlInfo.LoadXml(info);

        String revision = "N/A";

        foreach (XmlNode node in xmlInfo.ChildNodes)
          foreach (XmlNode innerNode in node.ChildNodes)
            if (innerNode.Name == "entry")
              foreach (XmlAttribute attribute in innerNode.Attributes)
                if (attribute.Name == "revision")
                {
                  revision = attribute.Value;
                  errorLevel = 0;
                }

        String svn_h = "//" + "\n" +
                       "// Generated by SVNAutomate." + "\n" +
                       "//" + "\n" + "\n" +
          //                       "#ifndef __SVN_H" + "\n" +
          //                       "#define __SVN_H" + "\n" + "\n" +
                       "#define SCD_PATCH_SVN " + revision;

        String current_svn_h = "";

        try
        { // load current svn.h into current_svn_h.
          FileStream fileStream = new FileStream(fileName, FileMode.Open);
          StreamReader streamReader = new StreamReader(fileStream);
          while (!streamReader.EndOfStream)
          {
            current_svn_h += streamReader.ReadLine() + "\n";
          }
          streamReader.Close();
          fileStream.Close();
        }
        catch(Exception) // no file or some other error.
        {
        }

        if ((!forceUpdate)&&(current_svn_h.Trim() != svn_h.Trim()))
        {
          try
          {
            FileStream fileStream = new FileStream(filePath, FileMode.Create);
            StreamWriter streamWriter = new StreamWriter(fileStream);
            streamWriter.Write(svn_h);
            didUpdate = true;
            streamWriter.Close();
            fileStream.Close();
          }
          catch(Exception e)
          {
            Console.WriteLine("Exception occurred in SVN process execution: " + e.Message);
            return 1;
          }
        }

        if (errorLevel != 0)
        {
          Console.WriteLine("Unable to find revision number:\n" + info);
          return 1;
        }
        else
        {
          if (didUpdate)
            Console.WriteLine("Updated/created file: " + fileName + "\n  (Full path expansion: " + filePath + ")");
          else
            Console.WriteLine("No changes, didn't update file: " + fileName + "\n  (Full path expansion: " + filePath + ")");

          return 0;
        }
      }
      catch (Exception e)
      {
        Console.WriteLine("Unable to process XML: " + e.Message + "\n" + info);
        return 1;
      }
    }
  }
}
