//================== SysCAD - Copyright Kenwalt (Pty) Ltd ===================
// $Nokeywords: $
//===========================================================================
/******************************* C3GMCRS.H *********************************/
#ifndef C3GMCRS
#define C3GMCRS

/*
#define     C3_ARC_PT0(A)       ((A)->arcseg.pt0)
#define     C3_ARC_PT1(A)       ((A)->arcseg.pt1)
#define     C3_ARC_D_VEC(A)     ((A)->arcseg.d_vec)
*/
#define     C3_ARC_ZERO_RAD(A)  ((A)->zero_rad)
#define     C3_ARC_SEG(A)       (&((A)->arcseg))

#endif  /* C3GMCRS */
