//================== SysCAD - Copyright Kenwalt (Pty) Ltd ===================
// $Nokeywords: $
//===========================================================================
/******************************** C3TPRIV.H ********************************/
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
/*!!!!!!!! (C) Copyright 1989, 1990, 1991 Building Block Software  !!!!!!!!*/
/*!!!!!!!!                    All rights reserved                  !!!!!!!!*/
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
#ifndef     C3TPRIV
#define     C3TPRIV
#include    <c3defs.h>
#ifdef  SPLINE
extern  REAL*       c3t_eval_hpt __(( HPT3 DUMMY0 , C3_TRANSFORM DUMMY1 ,
            HPT3 DUMMY2 )) ;
#endif
#endif /* C3TPRIV*/

