//================== SysCAD - Copyright Kenwalt (Pty) Ltd ===================
// $Nokeywords: $
//===========================================================================
/******************************** C3VPRIV.H ********************************/
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
/*!!!!!!!! (C) Copyright 1989, 1990, 1991 Building Block Software  !!!!!!!!*/
/*!!!!!!!!                    All rights reserved                  !!!!!!!!*/
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
#ifndef C3VPRIV
#define C3VPRIV
#include <c3defs.h>
extern  REAL        c3v_coord __(( PT3 DUMMY0 , PT3 DUMMY1 , PT3 DUMMY2 ,
            PT3 DUMMY3 )) ;
extern  void        c3v_plane_def __(( PT3 DUMMY0 , PT3 DUMMY1 [2],
            PT3 DUMMY2 , REAL* DUMMY3 , INT* DUMMY4 )) ;

#endif /*C3VPRIV*/

