//================== SysCAD - Copyright Kenwalt (Pty) Ltd ===================
// $Nokeywords: $
//===========================================================================
/****************************** DXTBLX.H ***********************************/ 
/*****************  Include file for DXF file manipulation  ****************/ 
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/ 
/*!!!!!!!! (C) Copyright 1989, 1990, 1991 Building Block Software   !!!!!!!*/
/*!!!!!!!!                    All rights reserved                   !!!!!!!*/ 
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/ 
#ifndef     DXTBLX 
#define     DXTBLX 

#include <qgldefs.h>
#include <dmdefs.h>

#ifdef DX_TBL_ON
#include    <dxtblxd.h>
#endif      /* DX_TBL_ON */
#include    <dxtbld.h>
#include    <dxtblm.h>
#ifdef DX_TBL_ON
#include    <dxtblxm.h>
#endif  /* DX_TBL_ON */

#endif     /*DXTBLX*/

