//================== SysCAD - Copyright Kenwalt (Pty) Ltd ===================
// $Nokeywords: $
//===========================================================================
/******************************* VPVDEFS.H *********************************/
/*************************** View prototypes *******************************/
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
/*!!!!!!!! (C) Copyright 1989, 1990, 1991 Building Block Software  !!!!!!!!*/
/*!!!!!!!!                    All rights reserved                  !!!!!!!!*/
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/

#ifndef VPVDEFS
#define VPVDEFS

#include <vpdefs.h>

extern  VP_VIEW vpv_copy __(( VP_VIEW DUMMY0 , VP_VIEW DUMMY1 )) ;
extern  VP_VIEW vpv_create __(( void )) ;
extern  void    vpv_free __(( VP_VIEW DUMMY0 )) ;

#endif /* VPDEFS */


