//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Configuration_Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Configuration_Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [General]
        ///Description=
        ///Std_Temp=293.16000000000003
        ///Std_Press=101.325
        ///Norm_Temp=298.16000000000003
        ///Norm_Press=101.325
        ///Minimum_Temp=273.16000000000003
        ///Maximum_Temp=2773.1599999999999
        ///Minimum_Press=5
        ///Maximum_Press=10000
        ///Atmospheric_Press= 101.287, -11.836e-3, 0.47931-6
        ///NumericStartingTagsBad=0
        ///NumericTagsBad=1
        ///UseStdFns4H2O=1
        ///Default_SpModel=Standard
        ///H2O_as_aqueous=1
        ///
        ///[Modes]
        ///Default_NetMode=Dynamic
        ///Probal_Allowed=1
        ///Probal_NodeMode=Direct
        ///Probal_FlowMode=Transfer
        ///Probal_HeatMode=Rigorous        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultInI {
            get {
                return ResourceManager.GetString("DefaultInI", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FunctionHS {
            get {
                object obj = ResourceManager.GetObject("FunctionHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InsertTabControlHS {
            get {
                object obj = ResourceManager.GetObject("InsertTabControlHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PropertiesHS {
            get {
                object obj = ResourceManager.GetObject("PropertiesHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sum {
            get {
                object obj = ResourceManager.GetObject("Sum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TextboxHS {
            get {
                object obj = ResourceManager.GetObject("TextboxHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
