//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Configuration_Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Configuration_Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H,1.00794
        ///He,4.002602
        ///Li,6.941
        ///Be,9.012182
        ///B,10.811
        ///C,12.0107
        ///N,14.0067
        ///O,15.9994
        ///F,18.9984032
        ///Ne,20.1797
        ///Na,22.98976928
        ///Mg,24.305
        ///Al,26.9815386
        ///Si,28.0855
        ///P,30.973762
        ///S,32.065
        ///Cl,35.453
        ///Ar,39.948
        ///K,39.0983
        ///Ca,40.078
        ///Sc,44.955912
        ///Ti,47.867
        ///V,50.9415
        ///Cr,51.9961
        ///Mn,54.938045
        ///Fe,55.845
        ///Co,58.933195
        ///Ni,58.6934
        ///Cu,63.546
        ///Zn,65.38
        ///Ga,69.723
        ///Ge,72.64
        ///As,74.9216
        ///Se,78.96
        ///Br,79.904
        ///Kr,83.798
        ///Rb,85.4678
        ///Sr,87.62
        ///Y,88.90585
        ///Zr,91.224
        ///Nb,92.90638
        ///Mo,95.96
        ///Tc,98
        ///Ru,101.07
        ///Rh,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AtmoicWts {
            get {
                return ResourceManager.GetString("AtmoicWts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [General]
        ///Description=
        ///Std_Temp=293.16000000000003
        ///Std_Press=101.325
        ///Norm_Temp=298.16000000000003
        ///Norm_Press=101.325
        ///Minimum_Temp=273.16000000000003
        ///Maximum_Temp=2773.1599999999999
        ///Minimum_Press=5
        ///Maximum_Press=10000
        ///Atmospheric_Press= 101.287, -11.836e-3, 0.47931-6
        ///NumericStartingTagsBad=0
        ///NumericTagsBad=1
        ///UseStdFns4H2O=1
        ///Default_SpModel=Standard
        ///H2O_as_aqueous=1
        ///
        ///[Modes]
        ///Default_NetMode=Dynamic
        ///Probal_Allowed=1
        ///Probal_NodeMode=Direct
        ///Probal_FlowMode=Transfer
        ///Probal_HeatMode=Rigorous        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultInI {
            get {
                return ResourceManager.GetString("DefaultInI", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FunctionHS {
            get {
                object obj = ResourceManager.GetObject("FunctionHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InsertTabControlHS {
            get {
                object obj = ResourceManager.GetObject("InsertTabControlHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PropertiesHS {
            get {
                object obj = ResourceManager.GetObject("PropertiesHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sum {
            get {
                object obj = ResourceManager.GetObject("Sum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TextboxHS {
            get {
                object obj = ResourceManager.GetObject("TextboxHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
