#pragma once

template <class T>
class CProxy_IScdDDEServerEvents : public IConnectionPointImpl<T, &__uuidof( _IScdDDEServerEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
