#pragma once

template <class T>
class CProxy_IScdOPCServerEvents : public IConnectionPointImpl<T, &__uuidof( _IScdOPCServerEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
