#pragma once

template <class T>
class CProxy_IScdIOMarshalEvents : public IConnectionPointImpl<T, &__uuidof( _IScdIOMarshalEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
