//================== SysCAD - Copyright Kenwalt (Pty) Ltd ===================
// $Nokeywords: $
//===========================================================================
// SysCAD Copyright Kenwalt (Pty) Ltd 1992

#ifndef  __CMDS_H
#define  __CMDS_H

// Command Identifiers

#define  ID_BMENU_01    101
#define  ID_BMENU_02    102
#define  ID_BMENU_03    103
#define  ID_BMENU_04    104
#define  ID_BMENU_05    105
#define  ID_BMENU_06    106
#define  ID_BMENU_07    107
#define  ID_BMENU_08    108
#define  ID_BMENU_09    109
#define  ID_BMENU_10    110
#define  ID_BMENU_11    111
#define  ID_BMENU_12    112
#define  ID_BMENU_13    113
#define  ID_BMENU_14    114
#define  ID_BMENU_15    115
#define  ID_BMENU_16    116
#define  ID_BMENU_17    117
#define  ID_BMENU_18    118
#define  ID_BMENU_19    119
#define  ID_BMENU_20    120
#define  ID_BMENU_21    121
#define  ID_BMENU_22    122
#define  ID_BMENU_23    123
#define  ID_BMENU_24    124
#define  ID_BMENU_25    125
#define  ID_BMENU_26    126
#define  ID_BMENU_27    127
#define  ID_BMENU_28    128
#define  ID_BMENU_29    129
#define  ID_BMENU_30    130
#define  ID_BMENU_31    131
#define  ID_BMENU_32    132
#define  ID_BMENU_33    133
#define  ID_BMENU_34    134
#define  ID_BMENU_35    135
#define  ID_BMENU_36    136
#define  ID_BMENU_37    137
#define  ID_BMENU_38    138
#define  ID_BMENU_39    139
#define  ID_BMENU_40    140
#define  ID_BMENU_41    141
#define  ID_BMENU_42    142
#define  ID_BMENU_43    143
#define  ID_BMENU_44    144
#define  ID_BMENU_45    145
#define  ID_BMENU_46    146
#define  ID_BMENU_47    147
#define  ID_BMENU_48    148
#define  ID_BMENU_49    149
#define  ID_BMENU_50    150

#define  ID_BMENU_CLS   190
#define  ID_BMENU_HLP   191
#define  ID_BMENU_NXT   192

#define  CM_SC_EDIT        201
#define  CM_SC_FILE        202
#define  CM_SC_ELMS        401
#define  CM_SC_DYNAMIC     402
#define  CM_SC_MICROSIM    403
#define  CM_SC_EXIT        404
#define  CM_SC_HELP           206

#define  CM_DYN_LOAD    501
#define  CM_DYN_SOLVE   502
#define  CM_DYN_CONVERT 503
#define  CM_DYN_HELP    504
#define  CM_DYN_FILE    505
#define  CM_DYN_ZOOM    506
#define  CM_DYN_C    507
#define  CM_DYN_D    508
#define  CM_DYN_E    509
#define  CM_DYN_F    510
#define  CM_DYN_G    511
#define  CM_DYN_H    512
#define  CM_DYN_I    513

#define  CM_MS_LOAD     601
#define  CM_MS_SOLVE    602


#define  IDM_BUMPINPUT   100

#endif
